server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/cmfz?useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 192.168.188.14
    port: 6379
    database: 0

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  type-aliases-package: com.baizhi.ljy.entity
  mapper-locations: classpath:com/baizhi/ljy/mapper/*.xml
logging:
  level:
    root: info
    com.baizhi.ljy.dao: debug
    com.baizhi.ljy.service: debug
    com.baizhi.ljy.controller: debug
